services:
  container_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
    restart: unless-stopped
    env_file:
      - .env.example
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - redis
      - db
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
volumes:
  redis:
    driver: local
